### ISSUE TITLE
Hello, about the ground truth about the fishyscapes benchmark...

### ISSUE THREAD

**Issue by suesuekkim** [giandbt/synboost#18]
Hi, I am trying to visualize your method and I have some questions about the label in the fishyscapes benchmark (lost and found, static).
I saw that the label that you used in the image_dissimilarity/test.py in below, and is it right that the anomaly objects are just masked in a border? 
![image_0](https://user-images.githubusercontent.com/78398919/180176493-48f76079-2c4e-4a7c-a0a1-f380aae0a4c5.png)
Here is the original image of the corresponding label.
![image_0](https://user-images.githubusercontent.com/78398919/180177025-78476a46-1f15-44a1-a262-616bf1004224.png)
I expected that inside the horse should be filled, so what's the exact ground trouth of this bench mark?

Also, I have another question, do we need to always preprocess all of the data to train? So to train with your method, it's like training the dissimilarity model, and use as an input of the file 'final_dataset' that you offered.

Is there any parallelized process of all? So like the input is the original image, and the output is the anomaly prediction.
I also saw your demo.py but it only does it for single sample.

Btw, thanks for your clean code and your contribution in this subject.

**Comment by carlosdavidardon** [comment]
I'm not the owner of this repo, but  as you expected, the horses (anomalies) are actually filled. The 'label' images use 3 values: 
0: not an anomaly
1: anomaly
255: ignore region

Since you are using a image viewer, the image is displayed in gray-scale, so the ignore area appears in white. While the anomaly region (value 1) is too close to black (value 0) we don't see the difference. The ignore area is used for the ego-vehicle, borders and other areas that we don't want to be taken into consideration for metrics. However, I'm not sure why the border of the anomalies are marked as ignore regions (maybe due to artifacts?). Here is a image where I replace the value 1 for 125, so it is displayed as gray:
![tmpxs7yviy2](https://user-images.githubusercontent.com/61714282/181436430-cddce776-627f-46d0-9906-462cc64ecd2f.PNG)

Regarding the dataset, as the owner stated in the readme: "In future releases, we will make one script to do all the pre-process automatically.". So there is no automatic way to do it for now. You can use the programs in the data_preparation directory to prepare the dataset by yourself. However, you will also need programs from image_dissimilarity/data to prepare the images with anomalies by replacing labels in the segmentation before the synthesis.
